### ISSUE TITLE
[XS] BC Parks DNS Update

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#296] opened 2023-12-13 01:13 UTC
This ticket is to track work on updating BC Parks DNS strategy

## Acceptance Criteria
- [ ] Export all of Go Daddy zone records for all BC Parks DNS into Route 53
- [ ] Change registrar name server from Go Daddy to Route 53
- [ ] Optional or at same time: completely change the registrar from Go Daddy to Route 53
- [ ] Connect with Rob about SSL Cert related to BC Parks AWS

## Notes
JUST DO IT RIGHT

**Comment by marklise** [comment] 2023-12-18 21:06
Updating estimation due to extra records not anticipated were there.

- blog.bcparks.ca is supposed to forward to engage.gov.bc.ca/bcparksblog/, but that currently does not work.
- dam.bcparks.ca is supposed to forward to http://bcparks.canadacentral.cloudapp.azure.com/resourcespace, but that currently does not work.
- discove.bcparks.ca is supposed to forward to https://bcparks.ca, but that currently does not work.

Need to confirm if these are ok to ignore (they are basically dead anyways).

**Comment by JLWade** [comment] 2023-12-18 21:12
Let me know if there is anything I can do to help :)

**Comment by marklise** [comment] 2023-12-18 22:10
There are a number of forwarding rules in place that need to be considered (ELB/NGINX):

- bcparksplates.ca => https://bcparks.ca/licence-plates/
- bcparksplates.com => https://bcparks.ca/licence-plates/
- discoverbcparks.ca => https://bcparks.ca/
- discoverbcparks.com => https://bcparks.ca/

**Comment by marklise** [comment] 2024-01-08 22:30
All 4 domains are fully working with their lambda redirects.  The last remaining thing to do is to migrate the entire godaddy account to AWS Route53 for domain registration.

**Comment by marklise** [comment] 2024-01-15 19:15
AWS Support ticket in progress.

**Comment by marklise** [comment] 2024-02-08 21:53
Transferring in progress:
- discoverbcparks.ca

Transferring complete:
- bcparks.ca
- bcparksplates.ca

Blocked on whois update delay:
- bcparksplates.com
- discoverbcparks.com

**Comment by marklise** [comment] 2024-02-13 21:28
Partial unblock. AWS Account has been identified, cleaned up the resources - confirmed that there was existing cert/cname set in that CloudFront configuration that was preventing our new account from configuring things for discovercamping.ca. This part is now complete and the account in question can be fully deleted.

**Comment by Dianadec** [comment] 2024-02-21 17:57
@marklise I added the SSL Cert AC to this card. Feel free to modify it

**Comment by marklise** [comment] 2024-02-26 22:26
SSL Certs have been created properly. The other team now has infrastructure issues separate from SSL configuration issues. We can complete this ticket now.

**Closed** 2024-02-26 22:26 UTC
