### ISSUE TITLE
Data Register -> Filter by protected area status does not function

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#244] opened 2023-11-29 21:44 UTC
Scenario:

* Navigate to the data register admin site on the TEST environment: https://test-data.bcparks.ca/admin/protected-areas
* Log in and navigate to the Manage Records page
* Now search for the keyword "park" and along with that try applying filters from the "Filter by protected area status"

Issue:

* The filters applied through the dropdown menu "Filter by protected area status" don't do anything to the search results.

Refer to the recording below for an example. 

https://github.com/bcgov/parks-data-register/assets/65190263/1ed7afb7-64f4-4cce-a5a9-c9f54dbcc418

**Comment by JLWade** [comment] 2023-11-30 00:53
This one seems important - will move into sprint. @cameronpettit is this currently blocked by #224?
I have a hunch that may be why it is not working.

**Comment by JLWade** [comment] 2023-11-30 01:05
getting this error:


![Image](https://github.com/bcgov/parks-data-register/assets/38668130/a5c5ae81-161b-44d1-b8bb-567b4c509e18)

**Comment by ashley-dhillon** [comment] 2023-12-01 17:45
This ticket may be a duplicate. Depends on if this is resolved through the completion of tickets Daniel is currently working on - to be confirmed.

**Comment by marklise** [comment] 2023-12-07 17:59
This is a dupe of #27.  I have added the filter criteria to #27 to ensure it's been captured. Closing this one.

**Closed by marklise** 2023-12-07 17:59 UTC
Labels: Data Register
