### ISSUE TITLE
UI Designs for Sites

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#238] opened 2023-11-28 18:09 UTC
This ticket is to utilize #223 and #125 and create designs for the implementation of sites into the data register. 

## Acceptance Criteria
- designs are added to implementation ticket #124 
- Any changes that come out of #223 will be reflected in the designs
## Notes
- designs are on the [Sites page in the Figma file](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=2096%3A3229&mode=design&t=M6ayrs5cjBcHqDKd-1)
- designs have been added to #124

**Comment by janemoxd** [comment] 2023-12-07 17:12
I'll go over this with both of you in our Tuesday meeting, but wanted to document it as well.

@meredithom I have added the [View Record page](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=3299%3A5591&mode=design&t=xJGS7bRvvjjjgy1k-1) to Release 2 section of the Figma. 

- Would be great if you could sanity check it and also review the questions in the notes. You may have some answers for those. 
- Since the flows and pages are the same as Protected Area, I didn't think devs would need wireframes for all the site edit flows. But if you think you/Daniel will need them, please create them.
- I did a [wireframe / exploration for the search](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=3161%3A15402&mode=design&t=xJGS7bRvvjjjgy1k-1) for sites. Passing this on to you to push forward and think through more. You'll see all my questions. May want to create a separate ticket for search?

@ndelraye Double checking if you know if Established / Repealed are the correct Statuses for Sites? If you don't know, could you please check with Glenna?

**Comment by ndelraye** [comment] 2023-12-07 17:43
Checked with Glenna re: Established/Repealed

- Established and Repealed are correct for Sites
- It will be the same established and repealed dates as the parent protected area 
-Sites are not treated like their own Legal establishment outside the larger protected area, just have a different name to track in the registry
- A site could be removed from the legal description of a protected area and the larger protected area will stay active (Repeal a site)
- If a protected area has sites associated to it and the protected area is repealed will it repeal all the related sites? - answer: Yes

- Confirmed sites will not have a pending status

 Note from Glenna she is thinking we will need another option other than Repealed in the future (for this stage were good with just repealed):
"Trying to think of other words that would apply to the next stage of the register when other names will need to come and go that are not legal in nature...'closed' 'cancelled'. But for this stage repealed will work for the protected area names and sites. "

**Comment by janemoxd** [comment] 2023-12-07 18:13
That is great info! Thank you. 

FYI all I added the above to our [DR Research page in Confluence](https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/UX+Research)

**Comment by janemoxd** [comment] 2023-12-08 00:25
In Data Register, site numbering is still TBD. Likely that:

Sites will be given a number starting from 1, and not necessarily a 2 digit number.  It likely/might be prefixed with ORCS.  This is not set in stone yet.
Site statuses:

Established and Repealed are the correct statuses for Sites

There is no pending status for sites
Most of the time, Sites will have the same established and repealed dates as the parent protected area

A site could be removed from the legal description of a protected area and the larger protected area will stay active (Repeal a site). A new Site could be added to an established protected area.

If a protected area has sites associated to it and the protected area is repealed, the sites will also be repealed

Confirmed sites will not have a pending status

**Comment by janemoxd** [comment] 2024-01-05 18:10
Designs are ready for review with the team. Not moving this ticket to done until team has reviewed designs and we have shared understanding / agreement.

**Comment by ashley-dhillon** [comment] 2024-01-15 23:06
Team reviewed the designs at refinement on Jan 9th with Glenna. Jane had a takeaway to confirm decision on leading zeros for Site ID's with Jess. Once confirmed, designs are good to go (assuming no changes need to be made to reflect leading zeros update).

**Comment by JLWade** [comment] 2024-01-15 23:32
Lets leave leading zero's in for ID for now as this is not an urgent change and we can move forward with designs as is.

**Comment by JLWade** [comment] 2024-01-15 23:32
moving to done

**Closed** 2024-02-27 23:18 UTC
