### ISSUE TITLE
[XL] Sites Implementation - API

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#332] opened 2024-01-09 18:46 UTC
**Description:**
Create necessary endpoints for consumers of the api to access sites. This includes BC Parks staff via data register admin UI and for subscribers accessing via api only.

**Acceptance Criteria:**
- Determine how to surface data model and data to consumers of the API
  - Frontend UI endpoint created to support #124 
  - API subscriber endpoint created to support api subscribers and access
- API usage plan and configuration is set up appropriately 

Notes:
- will likely need to be split into more than one ticket.
- blocked by #125 
- Dependency/relates to #326 (can be done in tandem but 326 can't be finished until 332 is done)
- Site business rules follow park name change business rules: https://teams.microsoft.com/l/message/19:163facd69a2e4fe1a14eac3ae95fb3c4@thread.tacv2/1709253521757?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1709252504020&teamName=External%3A%20Team%20Osprey&channelName=Dev%20Chat&createdTime=1709253521757

**Comment by jpeersoxd** [comment] 2024-04-09 21:38
As recommended by @cameronpettit , I'm adding any issues found while testing here.

**Comment by jpeersoxd** [comment] 2024-04-09 21:39
Issue found with displaying Site record (see #395). System generated details look incorrect: Type is Protected Area, where it should be Site.

<img width="957" alt="Screenshot 2024-04-09 at 12 43 25 PM" src="https://github.com/bcgov/parks-data-register/assets/65189530/cc847d3f-60a3-46ed-94c2-286598ec112b">

**Comment by cameronpettit** [comment] 2024-04-09 23:11
> Issue found with displaying Site record (see https://github.com/bcgov/parks-data-register/issues/395). System generated details look incorrect: Type is Protected Area, where it should be Site.

Now addressed in #454

**Comment by jpeersoxd** [comment] 2024-04-12 22:43
Issue found while testing #326 . To reproduce:

- Select a protected area
- Change its status to Repealed and select an effective date
- For the same protected area, edit and change the effective date
- See the error attached

<img width="1422" alt="Screenshot 2024-04-12 at 3 37 47 PM" src="https://github.com/bcgov/parks-data-register/assets/65189530/e23c466a-ef34-4cf2-bf2c-4055a9d19f54">

**Comment by JLWade** [comment] 2024-04-12 22:57
getting that same error - page gets stuck/frozen when I click save changes

**Comment by manuji** [comment] 2024-04-25 23:58
Tested on TEST: **Failed**
* The error mentioned in Jim's previous comment has not been fixed. 
* Moving to Todo. 



![Image](https://github.com/bcgov/parks-data-register/assets/65190263/e8a1e42d-0493-4b44-bed6-cf8dc0b827ce)

**Comment by cameronpettit** [comment] 2024-04-26 16:49
@manuji oops, this got fixed in https://github.com/bcgov/parks-data-register/commit/eb16c40918df84845bd7d7df3db1d4d3a21d36e1 - I had it done weeks ago but forgot to merge it before I left on vacation. Should be fixed in DEV already.

**Comment by manuji** [comment] 2024-04-26 16:54
Thanks you @cameronpettit , I will deploy and test :)

**Comment by manuji** [comment] 2024-04-26 19:54
Hi @cameronpettit , I retested this, but looks like there is an issue with the whole minor edit feature on a repealed Protected area object. When I try to edit the Effective date, it gives me the error below. 



![Image](https://github.com/bcgov/parks-data-register/assets/65190263/901a8f77-ddd4-4d2c-8c20-9109e6097141)

Could you please double check this on TEST environment?

**Comment by cameronpettit** [comment] 2024-04-26 20:40
Minor issue resulting from me merging the logic for both protected areas and sites together. Fixed in #462

**Comment by manuji** [comment] 2024-04-29 22:31
Tested on TEST: **Passed**
* Verified that this issue has been fixed. 
* Passing to PO review.

**Comment by JLWade** [comment] 2024-05-02 18:54
moving to done

**Closed by JLWade** 2024-05-02 18:54 UTC
Labels: Data Register
